### ISSUE TITLE
Confusing messaging ...

### ISSUE THREAD

**Issue by stephensong** [Microsoft/NoSQLProvider#29]
It's a bit disconcerting that the rest of the docs enthusiastically refer to this lib as one of the selling points for ReactXP, but one arrives here only to find the message:

   "For now, I would suggest not using this yet, as it requires some more work."

It would be nice if more information could be provided as to whether and when using this lib could be contemplated, what are the issues requiring work etc.

just sayin'.

**Comment by erictraut** [comment]
Can you provide more details about where you saw this message?

**Comment by erictraut** [comment]
Ah, never mind. You're referring to the README. Duh.

Yes, I agree that the message should be updated. @deregtd, do you want to do the honors?

**Comment by ms-deregtd** [comment]
Yep.  I'll work on that.  I just put up a quick change to the front page that points at an example, but I need to write some more full API docs.

**Comment by stephensong** [comment]
Many thanks for the quick response.  

I took a quick look at the example, and I noticed that it is written in the promise style rather than using async / await.  I assume that is because of the use of non-standard SyncTask promises - yes?  Does the use of SyncTask then prohibit the use of async / await  (... despite the presence of the  .then(...) calls)?  

Apologies if I'm being obtuse here. I'm trying to get my head around all this, but I find using async / await is my goto mode these days, and would be reluctant to adopt any library that discouraged use thereof.  I am also struggling to understand the need for "synchronous promises" - it sounds like standard node-style callbacks to me, modulo the cancellable bit.  Is the cancellability their raison d'etre?

Thanks again anyway.  It's all very intriguing.  I'll try to find time to have a play to see if I can get a better feel for what this actually means.  (Also, if you'd prefer I ask questions such as these in the gitter room I'm happy to do so.  I got a bit carried away here - I started out just saying thanks ; - )

**Comment by ms-deregtd** [comment]
Right now, TS doesn't allow alternate promise libraries for async/await.  We've made the team aware of our difficulties and they are working on a solution.  We'd love to be using async/await as well. :)

The synchronous promises are due to the need to get around the indexeddb transaction cancellation issue (I talk a little more about that in the new README file.)  In the end, though, they're also WAY faster to use than normal promises, since the event loop on most javascript engines is actually quite slow, so enqueueing work on it ends up slowing down your code flow by quite a bit in high-usage scenarios.

Feel free to ask questions as issues.  If you have them, others probably do too and it's good to have them documented as such!

**Comment by stephensong** [comment]
ok, cool.

Having struggled mightily myself with trying to use Bluebird with TS (eventually abandoning Bluebird altogether), I get the problem with async / await and alternate promises issue, 

As for "synchronous promises", I think my question is actually - why use "promises" at all?  I have always thought of promises themselves as an innately async construct - the .then(...) is allowed to happen asynchronously.  Is that not correct?  In my mind at least, that was what actually distinguished them from simple node-style callbacks.  Although, now that I think about it, I vaguely recall one of their selling points beings to lessen the tendency for nested callbacks to indent further and further to the right, so maybe I've answered my own question.  If so, istm a tad ott to write a whole library like SyncTasks simply to avoid having to nest callbacks.

many tias.

**Comment by ms-deregtd** [comment]
The promises RESOLVE synchronously, but they describe asynchronous behavior.  That simply means that if you do something like:

let a = 1;
SyncTasks.Resolved<void>().then(() => {
a = 2;
});
// a === 2 now

The database behavior is asynchronous -- when you do a get, it won't come back until some time in the future, so you want a promise for it.  You just need it to synchronously resolve with the result when it comes back from the database API, rather than waiting for one more full cycle of the event loop.  Does that make more sense?

**Comment by stephensong** [comment]
ahh - indeed it does!   That is to say, I at least _think_ I understand it now! <g>

cheers.
